config/routes.rb
Rails.application.routes.draw do

  get 'categories/index'
  get 'categories/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'comments/index'
  get 'comments/new'
  get 'comments/create'
  get 'comments/edit'
  get 'comments/update'
  get 'comments/destroy'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "categories#index"
  resources :bulletin_board_systems, only:[:create]
  resources :comments, only:[:create]
  resources :categories, only:[:show]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bbs_category.rb
class BbsCategory < ApplicationRecord
  belongs_to :bulletin_board_system
  belongs_to :category
end

app/models/bulletin_board_system.rb
class BulletinBoardSystem < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :bbs_categories, dependent: :destroy
  has_many :categories, through: :bbs_categories
  belongs_to :user
  accepts_nested_attributes_for :comments
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bbs_categories, dependent: :destroy
  has_many :bulletin_board_systems, through: :bbs_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :bulletin_board_system
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bulletin_board_system
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bulletin_board_systems_controller.rb
class BulletinBoardSystemsController < ApplicationController
  
  def create
    if user_signed_in?
      bbs = BulletinBoardSystem.new(bbs_params)
      bbs.user_id = current_user.id
      if bbs.save
        redirect_back(fallback_location: root_path)
      else
        render "new"
      end
    else
      redirect_to new_user_registration_path
    end
  end

  private
    def bbs_params
      params.require(:bulletin_board_system).permit(:title, category_ids: [], comments_attributes: [:body, :user_id])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @q = BulletinBoardSystem.ransack(params[:q])
    @results = @q.result
  end

  def show
    @category = Category.find(params[:id])
    @bulletin_board_systems = @category.bulletin_board_systems
    @comment = Comment.new
    @bbs = BulletinBoardSystem.new
    if user_signed_in?
      @bbs.comments.build(user_id: current_user.id)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    if user_signed_in?
      comment = Comment.new(comment_params)
      comment.user_id = current_user.id
      if comment.save
        redirect_back(fallback_location: root_path)
      else
        render "bulletin_board_systems/index"
      end
    else
      redirect_to new_user_registration_path
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body,:bulletin_board_system_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bulletin_board_systems_helper.rb
module BulletinBoardSystemsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/bulletin_board_systems/_index.html.erb
<% bulletin_board_systems.each do |bbs| %>
  <h2 class="thread-title"><%= bbs.title %></h2><br>
  <% bbs.comments.each_with_index do |comment,i| %>
    <h3><%= i + 1 %>
    名前：<%= bbs.user.user_name %>
    <%= comment.updated_at.strftime("%Y/%m/%d %H:%M") %></h3><br>
    <p class="comment-body"><%= comment.body %></p><br>
  <% end %>

  <%= form_for comment do |f| %>
    <%= f.text_area :body %>
    <%= f.hidden_field :bulletin_board_system_id, value: bbs.id %>
    <%= f.submit "書き込む" %>
  <% end %>

<% end %>

<%= render "bulletin_board_systems/new",bbs: bbs, category: category %>

app/views/bulletin_board_systems/_new.html.erb
<% if user_signed_in? %>
  <h2>新規スレッド作成</h2>
  <%= form_for bbs do |f| %>

    <%= f.label :title, "スレッドタイトル：" %>
    <%= f.text_field :title %><br>

    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name  %><br>

    <%= f.fields_for :comments do |c| %>
      <%= c.text_area :body, size: "45x5" %><br>
      <%= c.hidden_field :user_id, value: current_user.id %>
    <% end %>

    <%= f.submit "新規スレッド作成" %>

  <% end %>
<% end %>

app/views/categories/index.html.erb
<h1>FiveCannel</h1>

<h2>ジャンル一覧</h2><br>
<% @categories.each do |category| %>
  <%= link_to category.name, category_path(category.id) %><br>
<% end %>

<% if @results.any? %>
  <h2>スレッド一覧</h2><br>
  <%= search_form_for @q,url: root_path do |f| %>
    <%= f.search_field :title_cont %>
    <%= f.submit "検索" %>
  <% end %>
  <% @results.each do |result| %>
    <% result.categories.each do |category| %>
      <%= link_to result.title + "(#{category.name})" ,category_path(category.id) %><br>
    <% end %>
  <% end %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<%= render "bulletin_board_systems/index",bulletin_board_systems: @bulletin_board_systems, comment: @comment, bbs: @bbs, category: @category %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FiveChannel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <% if user_signed_in? %>
        <%= current_user.user_name %>
        <%= link_to "ログアウト",destroy_admin_user_session_path %>
      <% else %>
        <%= link_to "ゲストさん",new_user_registration_path %>
        <%= link_to "ログイン",new_user_session_path %>
      <% end %>
      <%= link_to "TOP", root_path %>
    </header>
    <%= yield %>
  </body>
</html>